"""Added indexes to Receipt model fields

Revision ID: f2d19bface07
Revises: 5c3948053cc1
Create Date: 2024-10-31 17:33:13.657561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2d19bface07'
down_revision: Union[str, None] = '5c3948053cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipt', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('receipt', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('receipt', 'payment_type',
               existing_type=postgresql.ENUM('CASH', 'CARD', name='paymenttype'),
               nullable=False)
    op.alter_column('receipt', 'payment_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('receipt_public_id_key', 'receipt', type_='unique')
    op.create_index(op.f('ix_receipt_created_at'), 'receipt', ['created_at'], unique=False)
    op.create_index(op.f('ix_receipt_public_id'), 'receipt', ['public_id'], unique=True)
    op.create_index(op.f('ix_receipt_user_id'), 'receipt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_user_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_public_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_created_at'), table_name='receipt')
    op.create_unique_constraint('receipt_public_id_key', 'receipt', ['public_id'])
    op.alter_column('receipt', 'payment_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('receipt', 'payment_type',
               existing_type=postgresql.ENUM('CASH', 'CARD', name='paymenttype'),
               nullable=True)
    op.alter_column('receipt', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('receipt', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
